project:
  type: website
  output-dir: docs

website:
  title: "Nick Soares"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog-posts.qmd

format:
  html:
    theme:
      light: cosmo
      dark: slate
    css: styles.css
    toc: true
    page-layout: full

editor: visual

